import { BrainCircuit, CheckCircle2, Loader2, Pencil, Trash2, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { api, apiErrorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import type { Candidate, CandidateInput, LocationType } from '../types'

export default function CandidateDetails(){
  const{user}=useAuth()
  const{id}=useParams(),navigate=useNavigate()
  const[candidate,setCandidate]=useState<Candidate|null>(null),[draft,setDraft]=useState<CandidateInput|null>(null)
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editing,setEditing]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  useEffect(()=>{if(!id)return;setLoading(true);api.candidates.get(id).then(value=>{setCandidate(value);const{id:_id,...input}=value;setDraft(input)}).catch(caught=>setError(apiErrorMessage(caught))).finally(()=>setLoading(false))},[id])
  async function save(){if(!id||!draft)return;setSaving(true);setError('');try{const updated=await api.candidates.update(id,draft);setCandidate(updated);const{id:_id,...input}=updated;setDraft(input);setEditing(false);setSuccess('Candidate changes saved.')}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving(false)}}
  async function remove(){if(!id||!candidate||!window.confirm(`Delete ${candidate.name}? This cannot be undone.`))return;try{await api.candidates.remove(id);navigate('/candidates')}catch(caught){setError(apiErrorMessage(caught))}}
  const update=<K extends keyof CandidateInput>(field:K,value:CandidateInput[K])=>setDraft(current=>current?{...current,[field]:value}:current)
  if(loading)return <main className="grid min-h-96 place-items-center"><Loader2 className="size-8 animate-spin text-blue-600"/></main>
  if(!candidate||!draft)return <main className="p-8"><p className="rounded-xl bg-rose-50 p-5 text-rose-700">{error||'Candidate not found.'}</p></main>
  return <main className="p-8">{error&&<p className="mb-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{success&&<p className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{success}</p>}<div className="card border-l-4 border-l-blue-600 p-7"><div className="flex items-start justify-between gap-5"><div className="flex items-center gap-5"><div className="grid size-20 place-items-center rounded-full bg-violet-100 text-xl font-bold text-violet-700">{draft.name.split(' ').map(part=>part[0]).join('')}</div><div><h1 className="page-title">{draft.name}</h1><p className="mt-1 text-slate-500">{draft.positionApplied} · {draft.resumeStatus}</p></div></div><div className="flex gap-2">{!editing&&<button onClick={()=>setEditing(true)} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><Pencil className="size-4 text-blue-600"/>Edit</button>}{user?.role==='ADMIN'&&<button onClick={remove} className="rounded-xl border p-2 text-rose-600" aria-label={`Delete ${candidate.name}`}><Trash2 className="size-4"/></button>}</div></div>
    {editing&&<div className="mt-6 grid gap-4 border-t pt-6 md:grid-cols-2"><Field label="Name" value={draft.name} onChange={value=>update('name',value)}/><Field label="Position applied" value={draft.positionApplied} onChange={value=>update('positionApplied',value)}/><Field label="Location" value={draft.location} onChange={value=>update('location',value)}/><Field label="Years experience" type="number" value={String(draft.yearsExperience)} onChange={value=>update('yearsExperience',Number(value))}/><Field label="Email" value={draft.email} onChange={value=>update('email',value)}/><Field label="Phone" value={draft.phone} onChange={value=>update('phone',value)}/><label className="text-sm font-semibold">Location type<select value={draft.locationType} onChange={event=>update('locationType',event.target.value as LocationType)} className="mt-1 w-full rounded-xl border px-3 py-2"><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><Field label="Skills" value={draft.skills.join(', ')} onChange={value=>update('skills',value.split(',').map(item=>item.trim()).filter(Boolean))}/><div className="flex gap-3 md:col-span-2"><button onClick={save} disabled={saving} className="grad-accent rounded-xl px-5 py-2 text-sm font-semibold text-white">{saving?'Saving…':'Save'}</button><button onClick={()=>{const{id:_id,...input}=candidate;setDraft(input);setEditing(false)}} className="rounded-xl border px-5 py-2 text-sm font-semibold">Cancel</button></div></div>}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[.8fr_2fr]"><div className="card p-7"><h2 className="text-xl font-bold">AI Match Score</h2><p className="mt-3 text-5xl font-bold text-blue-600">{candidate.matchScore}%</p><div className="mt-8 h-2 rounded-full bg-slate-100"><div className="grad-accent h-full rounded-full" style={{width:`${candidate.matchScore}%`}}/></div><div className="mt-7 space-y-2 text-sm text-slate-600"><p><b>Location:</b> {candidate.location} ({candidate.locationType})</p><p><b>Experience:</b> {candidate.yearsExperience} years</p><p><b>Availability:</b> {candidate.availability||'Not provided'}</p><p><b>Education:</b> {candidate.education||'Not provided'}</p></div></div><div className="card p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><BrainCircuit className="text-blue-600"/>Automated Profile Overview</h2><p className="mt-5 leading-7 text-slate-600">{candidate.summary||'No AI summary is available yet.'}</p><div className="mt-7 grid gap-6 border-t pt-6 sm:grid-cols-2"><div><h3 className="font-semibold">Strengths</h3>{candidate.strengths.length?candidate.strengths.map(item=><p key={item} className="mt-3 flex gap-2 text-sm text-slate-600"><CheckCircle2 className="size-4 shrink-0 text-emerald-500"/>{item}</p>):<p className="mt-2 text-sm text-slate-400">None recorded.</p>}</div><div><h3 className="font-semibold">Development areas</h3>{candidate.weaknesses.length?candidate.weaknesses.map(item=><p key={item} className="mt-3 flex gap-2 text-sm text-slate-600"><XCircle className="size-4 shrink-0 text-amber-500"/>{item}</p>):<p className="mt-2 text-sm text-slate-400">None recorded.</p>}</div></div></div></div>
    <section className="card mt-6 p-7"><h2 className="text-xl font-bold">Notes</h2><textarea value={draft.notes} onChange={event=>update('notes',event.target.value)} placeholder="Add interview notes or follow-up details..." className="mt-4 min-h-28 w-full rounded-xl border p-3 text-sm"/><button onClick={save} disabled={saving||draft.notes===candidate.notes} className="grad-accent mt-3 rounded-lg px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Save notes</button></section>
  </main>
}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 font-normal"/></label>}
