import { Clock3, Grid2X2, List, Loader2, MapPin, Search, SlidersHorizontal, UserCheck, X } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { api, apiErrorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import Badge from '../components/ui/Badge'
import type { Candidate, CandidateInput, Job, LocationType, ResumeStatus } from '../types'

type Tab='all'|'shortlisted'|'rejected'
type Sort='matchScore'|'name'|'experience'
const emptyCandidate:CandidateInput={name:'',positionApplied:'',jobId:'',yearsExperience:0,skills:[],education:'',languages:[],location:'',locationType:'Remote',email:'',phone:'',resumeStatus:'New',matchScore:0,availability:'',summary:'',strengths:[],weaknesses:[],experienceTimeline:[],certificates:[],notes:''}
const getTab=(value:string|null):Tab=>value==='shortlisted'||value==='rejected'?value:'all'

export default function CandidateManagement(){
  const{user}=useAuth()
  const[params,setParams]=useSearchParams(),tab=getTab(params.get('tab'))
  const[candidates,setCandidates]=useState<Candidate[]>([]),[jobs,setJobs]=useState<Job[]>([]),[pagination,setPagination]=useState({page:1,total:0,totalPages:1,limit:6})
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const[page,setPage]=useState(1),[search,setSearch]=useState(''),[sortBy,setSortBy]=useState<Sort>('matchScore')
  const[view,setView]=useState<'grid'|'list'>('grid'),[filterOpen,setFilterOpen]=useState(false),[minimumScore,setMinimumScore]=useState(0),[locationType,setLocationType]=useState<'all'|LocationType>('all')
  const[selected,setSelected]=useState<string[]>([]),[comparisonOpen,setComparisonOpen]=useState(false),[addOpen,setAddOpen]=useState(false),[form,setForm]=useState<CandidateInput>(emptyCandidate)
  const[skillsText,setSkillsText]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await api.candidates.list({search:search.trim()||undefined,minMatchScore:minimumScore||undefined,locationType:locationType==='all'?undefined:locationType,status:tab==='shortlisted'?'Shortlisted':tab==='rejected'?'Rejected':undefined,sortBy,page,limit:6});setCandidates(result.data);setPagination(result.pagination)}catch(caught){setError(apiErrorMessage(caught))}finally{setLoading(false)}},[search,minimumScore,locationType,tab,sortBy,page])
  useEffect(()=>{const timer=window.setTimeout(load,250);return()=>window.clearTimeout(timer)},[load])
  useEffect(()=>{api.jobs.list().then(setJobs).catch(caught=>setError(apiErrorMessage(caught)))},[])
  useEffect(()=>setPage(1),[search,minimumScore,locationType,tab,sortBy])
  const selectTab=(next:Tab)=>next==='all'?setParams({}):setParams({tab:next})
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):current.length<3?[...current,id]:current)
  async function status(id:string,status:Extract<ResumeStatus,'Screened'|'Shortlisted'|'Rejected'>){try{await api.candidates.updateStatus(id,status);await load()}catch(caught){setError(apiErrorMessage(caught))}}
  async function add(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await api.candidates.create({...form,skills:split(skillsText)});setForm(emptyCandidate);setSkillsText('');setAddOpen(false);await load()}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving(false)}}
  async function purgeRetention(){if(!window.confirm('Permanently delete every candidate older than the configured retention period? This cannot be undone.'))return;setSaving(true);setError('');try{const result=await api.candidates.purgeRetention();window.alert(`${result.deleted} retained candidate record(s) were permanently deleted.`);await load()}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving(false)}}
  function openAdd(){const job=jobs.find(item=>item.status==='Open')||jobs[0];setForm({...emptyCandidate,yearsExperience:0,jobId:job?.id||'',positionApplied:job?.title||''});setSkillsText('');setAddOpen(true)}
  function selectJob(jobId:string){const job=jobs.find(item=>item.id===jobId);setForm(current=>({...current,jobId,positionApplied:job?.title||''}))}
  const update=<K extends keyof CandidateInput>(field:K,value:CandidateInput[K])=>setForm(current=>({...current,[field]:value}))
  const selectedCandidates=candidates.filter(candidate=>selected.includes(candidate.id))
  return <main className="p-8"><div className="flex items-start justify-between gap-4"><div><h1 className="page-title">Candidate Management</h1><p className="muted mt-1">Analyze and manage talent with API-powered filtering.</p></div><div className="flex gap-2">{user?.role==='ADMIN'&&<button onClick={purgeRetention} disabled={saving} className="rounded-lg border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700">Run retention purge</button>}<button onClick={openAdd} className="grad-accent rounded-lg px-5 py-2.5 text-sm font-semibold text-white">+ Add Candidate</button></div></div>
    <div className="mt-7 flex flex-wrap items-center justify-between gap-3"><div className="rounded-xl border border-slate-200 bg-slate-100 p-1 text-sm font-medium">{([['all','All Candidates'],['shortlisted','Shortlisted'],['rejected','Rejected']] as const).map(([value,label])=><button key={value} onClick={()=>selectTab(value)} className={`rounded-lg px-5 py-2 ${tab===value?'bg-white text-blue-600 shadow-sm':'text-slate-500'}`}>{label}{value==='all'?` (${pagination.total})`:''}</button>)}</div><div className="flex flex-wrap gap-3"><label className="flex items-center gap-2 rounded-xl border bg-white px-4"><Search className="size-4 text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} className="w-40 py-2.5 text-sm outline-none" placeholder="Search candidates"/></label><select value={sortBy} onChange={event=>setSortBy(event.target.value as Sort)} className="rounded-xl border bg-white px-3 text-sm"><option value="matchScore">AI Match Score</option><option value="name">Name</option><option value="experience">Experience</option></select><div className="flex rounded-xl border bg-white p-1"><button onClick={()=>setView('grid')} className={`rounded-lg p-2 ${view==='grid'?'bg-slate-100 text-blue-600':'text-slate-400'}`}><Grid2X2 className="size-4"/></button><button onClick={()=>setView('list')} className={`rounded-lg p-2 ${view==='list'?'bg-slate-100 text-blue-600':'text-slate-400'}`}><List className="size-4"/></button></div><button onClick={()=>setFilterOpen(value=>!value)} className="rounded-xl border bg-white p-3"><SlidersHorizontal className="size-4"/></button></div></div>
    {filterOpen&&<section className="card mt-4 grid gap-5 p-5 sm:grid-cols-2"><label className="text-sm font-semibold">Minimum score: {minimumScore}%<input type="range" min="0" max="100" value={minimumScore} onChange={event=>setMinimumScore(Number(event.target.value))} className="mt-3 w-full accent-blue-600"/></label><label className="text-sm font-semibold">Location type<select value={locationType} onChange={event=>setLocationType(event.target.value as 'all'|LocationType)} className="mt-2 w-full rounded-lg border bg-white px-3 py-2"><option value="all">All</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label></section>}
    {error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    {loading?<div className="grid h-56 place-items-center"><Loader2 className="size-7 animate-spin text-blue-600"/></div>:<div className={`mt-7 gap-5 ${view==='grid'?'grid md:grid-cols-2 xl:grid-cols-3':'space-y-3'}`}>{candidates.map(candidate=><article key={candidate.id} className={`card relative p-5 ${view==='list'?'md:flex md:items-center md:gap-7':''}`}><label className="absolute right-4 top-4 z-10 text-xs font-semibold"><input type="checkbox" checked={selected.includes(candidate.id)} onChange={()=>toggle(candidate.id)} disabled={!selected.includes(candidate.id)&&selected.length===3} className="mr-1 accent-blue-600"/>Compare</label><Link to={`/candidates/${candidate.id}`} className="block min-w-0 flex-1"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-full bg-violet-100 font-bold text-violet-700">{candidate.name.split(' ').map(value=>value[0]).join('')}</div><div><h2 className="font-bold">{candidate.name}</h2><p className="text-sm text-slate-500">{candidate.positionApplied}</p></div></div><div className="mt-4 flex gap-4 text-xs text-slate-500"><span className="flex gap-1"><MapPin className="size-3"/>{candidate.location}</span><span className="flex gap-1"><Clock3 className="size-3"/>{candidate.yearsExperience} years</span></div><div className="mt-5 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-700">AI MATCH SCORE <span className="float-right">{candidate.matchScore}%</span></div><div className="mt-4 flex flex-wrap gap-1.5">{candidate.skills.map(skill=><Badge key={skill} className="bg-violet-50 text-violet-600">{skill}</Badge>)}</div></Link><div className={`mt-4 flex gap-2 ${view==='list'?'md:mt-0 md:flex-col':''}`}><button onClick={()=>status(candidate.id,candidate.resumeStatus==='Shortlisted'?'Screened':'Shortlisted')} className={`flex items-center justify-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold ${candidate.resumeStatus==='Shortlisted'?'border-emerald-200 bg-emerald-50 text-emerald-700':''}`}><UserCheck className="size-4"/>{candidate.resumeStatus==='Shortlisted'?'Unshortlist':'Shortlist'}</button><button onClick={()=>status(candidate.id,'Rejected')} className="rounded-lg border px-3 py-2 text-xs font-semibold text-rose-600">Reject</button></div></article>)}</div>}
    {!loading&&!candidates.length&&<div className="card mt-7 p-12 text-center text-sm text-slate-500">No candidates match these filters.</div>}
    <div className="mt-6 flex justify-center gap-3"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-40">Previous</button><span className="py-2 text-sm text-slate-500">Page {pagination.page} of {Math.max(1,pagination.totalPages)}</span><button disabled={page>=pagination.totalPages} onClick={()=>setPage(value=>value+1)} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-40">Next</button></div>
    {selected.length>=2&&<button onClick={()=>setComparisonOpen(true)} className="grad-accent fixed bottom-6 right-6 z-20 rounded-xl px-5 py-3 text-sm font-semibold text-white shadow-lg">Compare Selected ({selected.length})</button>}
    {comparisonOpen&&<div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold">Candidate Comparison</h2><button onClick={()=>setComparisonOpen(false)}><X/></button></div><div className="mt-6 grid gap-4 md:grid-cols-3">{selectedCandidates.map(candidate=><article key={candidate.id} className="rounded-xl border p-4"><h3 className="font-bold">{candidate.name}</h3><p className="text-sm text-slate-500">{candidate.positionApplied}</p><p className="mt-4 text-2xl font-bold text-blue-600">{candidate.matchScore}%</p><p className="mt-3 text-sm">{candidate.yearsExperience} years · {candidate.education}</p><p className="mt-2 text-sm">{candidate.skills.join(', ')}</p></article>)}</div></div></div>}
    {addOpen&&<div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={add} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Add Candidate</h2><p className="mt-1 text-sm text-slate-500">Save a candidate to the backend.</p></div><button type="button" onClick={()=>setAddOpen(false)}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Full name" value={form.name} onChange={value=>update('name',value)}/><label className="text-sm font-semibold">Job<select required value={form.jobId} onChange={event=>selectJob(event.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2 font-normal"><option value="">Select a job</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.title} — {job.status}</option>)}</select></label><Field label="Position applied" value={form.positionApplied} onChange={value=>update('positionApplied',value)}/><Field label="Email" value={form.email} onChange={value=>update('email',value)}/><Field label="Phone" value={form.phone} onChange={value=>update('phone',value)}/><Field label="Location" value={form.location} onChange={value=>update('location',value)}/><Field label="Years experience" type="number" min={0} value={String(form.yearsExperience)} onChange={value=>update('yearsExperience',Math.max(0,Number(value)||0))}/><Field label="Skills (comma separated)" value={skillsText} onChange={setSkillsText}/><label className="text-sm font-semibold">Location type<select value={form.locationType} onChange={event=>update('locationType',event.target.value as LocationType)} className="mt-1 w-full rounded-xl border px-3 py-2"><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><Field label="Availability" value={form.availability} onChange={value=>update('availability',value)}/></div>{!jobs.length&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-700">Create a job before adding a candidate.</p>}{error&&<p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setAddOpen(false)} className="rounded-xl border px-5 py-2">Cancel</button><button disabled={saving||!jobs.length} className="grad-accent rounded-xl px-5 py-2 font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Add Candidate'}</button></div></form></div>}
  </main>
}
const split=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
function Field({label,value,onChange,type='text',min}:{label:string;value:string;onChange:(value:string)=>void;type?:string;min?:number}){return <label className="text-sm font-semibold">{label}<input required type={type} min={min} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 font-normal"/></label>}
