import { BrainCircuit, BriefcaseBusiness, CalendarDays, Clock3, FileText, Loader2, Trash2, UserCheck, UserMinus, Users, X } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, apiErrorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import StatCard from '../components/ui/StatCard'
import type { Candidate, DashboardStats, Interview, InterviewInput, InterviewType, PipelinePoint, Stat } from '../types'

const blankInterview:InterviewInput={candidateId:'',date:'',time:'',interviewer:'',type:'Video',locationOrLink:'',notes:''}
export default function Dashboard(){
  const{user}=useAuth(),navigate=useNavigate()
  const[stats,setStats]=useState<DashboardStats|null>(null),[pipeline,setPipeline]=useState<PipelinePoint[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[interviews,setInterviews]=useState<Interview[]>([])
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[months,setMonths]=useState(6),[scheduleOpen,setScheduleOpen]=useState(false),[form,setForm]=useState<InterviewInput>(blankInterview)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[summary,history,candidatePage,upcoming]=await Promise.all([api.stats.dashboard(),api.stats.pipeline(),api.candidates.list({limit:100}),api.interviews.list({upcoming:true})]);setStats(summary);setPipeline(history);setCandidates(candidatePage.data);setInterviews(upcoming)}catch(caught){setError(apiErrorMessage(caught))}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  async function schedule(event:FormEvent){event.preventDefault();if(!form.candidateId||!form.date||!form.time||!form.interviewer.trim()){setError('Candidate, UTC date, UTC time, and interviewer are required.');return}setSaving(true);setError('');try{await api.interviews.create({...form,interviewer:form.interviewer.trim(),locationOrLink:form.locationOrLink||undefined});setForm(blankInterview);setScheduleOpen(false);setSuccess('Interview scheduled. Candidate status and notifications were updated.');await load()}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving(false)}}
  async function remove(interview:Interview){if(!window.confirm(`Remove the interview with ${interview.candidate.name}?`))return;try{await api.interviews.remove(interview.id);setInterviews(current=>current.filter(item=>item.id!==interview.id));setSuccess('Interview removed.')}catch(caught){setError(apiErrorMessage(caught))}}
  const cards:Stat[]=stats?[
    {label:'Total Candidates',value:String(stats.totalCandidates),change:'Live',trend:'up',icon:Users,tone:'blue'},
    {label:'Screened',value:String(stats.filteredCandidates),change:'Filtered',trend:'up',icon:FileText,tone:'purple'},
    {label:'Shortlisted',value:String(stats.shortlisted),change:'Live',trend:'up',icon:UserCheck,tone:'blue'},
    {label:'Rejected',value:String(stats.rejected),change:'Live',trend:'down',icon:UserMinus,tone:'slate'},
  ]:[]
  const destination=(label:string)=>label==='Shortlisted'?'/candidates?tab=shortlisted':label==='Rejected'?'/candidates?tab=rejected':'/candidates'
  return <main className="p-8"><section className="card bg-gradient-to-r from-white to-blue-50 px-9 py-8"><h1 className="text-3xl font-bold">Welcome back, {user?.name||'Recruiter'}</h1><p className="mt-2 text-slate-500">Review live candidate activity for <strong className="text-blue-600">{user?.companyName}</strong>.</p><div className="mt-5 flex flex-wrap gap-3"><Link to="/ai-analysis" className="grad-accent flex items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold text-white"><BrainCircuit className="size-4"/>Run AI Analysis</Link><button onClick={()=>setScheduleOpen(true)} className="flex items-center gap-2 rounded-lg border bg-white px-5 py-2.5 text-sm font-semibold"><CalendarDays className="size-4"/>Schedule Interview</button><Link to="/jobs" className="flex items-center gap-2 rounded-lg border bg-white px-5 py-2.5 text-sm font-semibold"><BriefcaseBusiness className="size-4"/>Manage Jobs</Link></div></section>
    {error&&<p role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}{success&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-700">{success}</p>}
    {loading?<div className="grid h-48 place-items-center"><Loader2 className="size-8 animate-spin text-blue-600"/></div>:<section className="my-9 grid grid-cols-2 divide-x lg:grid-cols-4">{cards.map(card=><StatCard key={card.label} stat={card} onClick={()=>navigate(destination(card.label))}/>)}</section>}
    <section className="grid gap-6 xl:grid-cols-[2fr_1fr]"><div className="card p-7"><div className="mb-6 flex justify-between"><div><h2 className="text-xl font-bold">Recruitment Pipeline</h2><p className="muted">Historical candidate progression</p></div><select value={months} onChange={event=>setMonths(Number(event.target.value))} className="rounded-lg border px-3 text-xs"><option value={3}>Last 3 Months</option><option value={6}>Last 6 Months</option><option value={12}>Last 12 Months</option></select></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={pipeline.slice(-months)}><CartesianGrid stroke="#e8ebf0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area type="monotone" dataKey="screened" stroke="#2563eb" fill="#dbeafe"/><Area type="monotone" dataKey="shortlisted" stroke="#7c3aed" fill="#ede9fe"/></AreaChart></ResponsiveContainer></div></div>
      <div className="card p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Upcoming Interviews</h2><p className="muted">{interviews.length} scheduled</p></div><CalendarDays className="size-5 text-blue-600"/></div><div className="mt-5 max-h-72 space-y-3 overflow-y-auto">{interviews.length?interviews.map(interview=><article key={interview.id} className="rounded-xl border p-4"><div className="flex justify-between gap-2"><div><h3 className="text-sm font-bold">{interview.candidate.name}</h3><p className="text-xs text-violet-600">{interview.type} · {interview.interviewer}</p></div><button onClick={()=>remove(interview)} aria-label={`Remove interview with ${interview.candidate.name}`} className="text-rose-500"><Trash2 className="size-4"/></button></div><p className="mt-3 flex items-center gap-1 text-xs text-slate-500"><Clock3 className="size-3"/>{new Date(interview.startsAt).toLocaleString()}</p>{interview.locationOrLink&&<p className="mt-2 truncate text-xs text-blue-600">{interview.locationOrLink}</p>}</article>):<p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No upcoming interviews.</p>}</div></div></section>
    {scheduleOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><form onSubmit={schedule} className="card w-full max-w-2xl p-6 sm:p-8"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Schedule interview</h2><p className="mt-1 text-sm text-slate-500">Date and time are entered in UTC.</p></div><button type="button" onClick={()=>setScheduleOpen(false)}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Candidate<select required value={form.candidateId} onChange={event=>setForm({...form,candidateId:event.target.value})} className="mt-1 w-full rounded-lg border bg-white px-3 py-2.5"><option value="">Select candidate</option>{candidates.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name} — {candidate.positionApplied}</option>)}</select></label><Field label="Date (UTC)" type="date" value={form.date} onChange={value=>setForm({...form,date:value})}/><Field label="Time (UTC)" type="time" value={form.time} onChange={value=>setForm({...form,time:value})}/><Field label="Interviewer" value={form.interviewer} onChange={value=>setForm({...form,interviewer:value})}/><label className="text-sm font-semibold">Type<select value={form.type} onChange={event=>setForm({...form,type:event.target.value as InterviewType})} className="mt-1 w-full rounded-lg border bg-white px-3 py-2.5"><option>Phone</option><option>Video</option><option>On-site</option></select></label><div className="sm:col-span-2"><Field required={false} label="Location or meeting link" value={form.locationOrLink||''} onChange={value=>setForm({...form,locationOrLink:value})}/></div><label className="text-sm font-semibold sm:col-span-2">Notes<textarea value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})} className="mt-1 min-h-24 w-full rounded-lg border p-3 font-normal"/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setScheduleOpen(false)} className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="grad-accent rounded-lg px-5 py-2.5 text-sm font-semibold text-white">{saving?'Scheduling…':'Schedule interview'}</button></div></form></div>}
  </main>
}
function Field({label,value,onChange,type='text',required=true}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input required={required} type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 h-11 w-full rounded-lg border px-3 font-normal"/></label>}
