import { BriefcaseBusiness, Loader2, Pencil, Plus, Search, Trash2, Users, X } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { api, apiErrorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import Badge from '../components/ui/Badge'
import type { Job, JobInput, JobStatus, LocationType } from '../types'

const emptyJob:JobInput={title:'',department:'',location:'',locationType:'Remote',requiredSkills:[],requiredExperience:'',education:'',languages:[],status:'Draft'}
const statusStyles:Record<JobStatus,string>={Open:'bg-emerald-100 text-emerald-700',Closed:'bg-slate-100 text-slate-600',Draft:'bg-amber-100 text-amber-700'}

export default function JobManagement(){
  const{user}=useAuth()
  const[jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const[isFormOpen,setIsFormOpen]=useState(false),[editingJob,setEditingJob]=useState<Job|null>(null),[form,setForm]=useState<JobInput>(emptyJob)
  const[searchQuery,setSearchQuery]=useState(''),[statusFilter,setStatusFilter]=useState<'All'|JobStatus>('All')
  const load=useCallback(async()=>{setLoading(true);setError('');try{setJobs(await api.jobs.list({search:searchQuery.trim()||undefined,status:statusFilter==='All'?undefined:statusFilter}))}catch(caught){setError(apiErrorMessage(caught))}finally{setLoading(false)}},[searchQuery,statusFilter])
  useEffect(()=>{const timer=window.setTimeout(load,250);return()=>window.clearTimeout(timer)},[load])
  const openNew=()=>{setEditingJob(null);setForm(emptyJob);setIsFormOpen(true)}
  const openEdit=(job:Job)=>{const{id:_id,applicants:_applicants,postedDate:_postedDate,...input}=job;setEditingJob(job);setForm(input);setIsFormOpen(true)}
  const close=()=>{setIsFormOpen(false);setEditingJob(null);setError('')}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{if(editingJob)await api.jobs.update(editingJob.id,form);else await api.jobs.create(form);close();await load()}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving(false)}}
  async function remove(job:Job){if(!window.confirm(`Delete "${job.title}"? This cannot be undone.`))return;try{await api.jobs.remove(job.id);await load()}catch(caught){setError(apiErrorMessage(caught))}}
  async function changeStatus(job:Job,status:JobStatus){try{const{id:_id,applicants:_applicants,postedDate:_postedDate,...input}=job;await api.jobs.update(job.id,{...input,status});await load()}catch(caught){setError(apiErrorMessage(caught))}}
  const update=<K extends keyof JobInput>(field:K,value:JobInput[K])=>setForm(current=>({...current,[field]:value}))
  return <main className="p-8"><div className="flex items-start justify-between gap-4"><div><h1 className="page-title">Job Management</h1><p className="muted mt-2">Create and manage your open positions.</p></div><button onClick={openNew} className="grad-accent inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold text-white"><Plus className="size-4"/>New job</button></div>
    <div className="mt-7 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} placeholder="Search by title or department" className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-blue-500"/></label><label className="flex items-center gap-2 text-sm font-medium text-slate-600">Status<select value={statusFilter} onChange={event=>setStatusFilter(event.target.value as 'All'|JobStatus)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5"><option>All</option><option>Open</option><option>Closed</option><option>Draft</option></select></label></div>
    {error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    {loading?<div className="grid h-56 place-items-center"><Loader2 className="size-7 animate-spin text-blue-600"/></div>:<section className="mt-5 grid gap-5 lg:grid-cols-2">{jobs.map(job=><article key={job.id} className="card p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><BriefcaseBusiness className="size-5 text-blue-600"/><h2 className="font-bold">{job.title}</h2></div><p className="muted mt-2">{job.department} · {job.location} · {job.locationType}</p></div><div className="flex flex-col items-end gap-2"><Badge className={statusStyles[job.status]}>{job.status}</Badge><select aria-label={`Change ${job.title} status`} value={job.status} onChange={event=>changeStatus(job,event.target.value as JobStatus)} className="rounded-md border border-slate-200 px-2 py-1 text-xs"><option>Open</option><option>Closed</option><option>Draft</option></select></div></div><div className="mt-4 flex flex-wrap gap-2">{job.requiredSkills.map(skill=><Badge key={skill} className="bg-violet-50 text-violet-700">{skill}</Badge>)}</div><p className="mt-4 text-sm text-slate-600">{job.requiredExperience||'Experience not specified'} · {job.education||'Education not specified'}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="inline-flex items-center gap-1.5 text-sm text-slate-500"><Users className="size-4"/>{job.applicants} applicants</span><div><button onClick={()=>openEdit(job)} className="rounded-lg p-2 text-blue-700 hover:bg-blue-50"><Pencil className="size-4"/></button>{user?.role==='ADMIN'&&<button onClick={()=>remove(job)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label={`Delete ${job.title}`}><Trash2 className="size-4"/></button>}</div></div></article>)}</section>}
    {!loading&&!jobs.length&&<div className="card mt-5 p-10 text-center text-sm text-slate-500">No jobs match your search.</div>}
    {isFormOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4"><form onSubmit={submit} className="card max-h-[90vh] w-full max-w-2xl overflow-y-auto p-6 sm:p-8"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{editingJob?'Edit job':'New job'}</h2><p className="muted mt-1">Enter the requirements used for candidate matching.</p></div><button type="button" onClick={close}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Job title" value={form.title} onChange={value=>update('title',value)}/><Field label="Department" value={form.department} onChange={value=>update('department',value)}/><Field label="Location" value={form.location} onChange={value=>update('location',value)}/><Select label="Location type" value={form.locationType} options={['Remote','Hybrid','On-site']} onChange={value=>update('locationType',value as LocationType)}/><Field label="Required experience" value={form.requiredExperience} onChange={value=>update('requiredExperience',value)}/><Field label="Education" value={form.education} onChange={value=>update('education',value)}/><Field label="Skills (comma separated)" value={form.requiredSkills.join(', ')} onChange={value=>update('requiredSkills',split(value))}/><Field label="Languages (comma separated)" value={form.languages.join(', ')} onChange={value=>update('languages',split(value))}/><Select label="Status" value={form.status} options={['Open','Closed','Draft']} onChange={value=>update('status',value as JobStatus)}/></div>{error&&<p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-lg px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="grad-accent rounded-lg px-4 py-2.5 text-sm font-semibold text-white">{saving?'Saving…':editingJob?'Save changes':'Create job'}</button></div></form></div>}
  </main>
}
const split=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm font-medium">{label}<input required value={value} onChange={event=>onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 outline-none focus:border-blue-500"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="text-sm font-medium">{label}<select value={value} onChange={event=>onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5">{options.map(option=><option key={option}>{option}</option>)}</select></label>}
