import { Bell, Building2, KeyRound, Loader2, UserPlus, UserRound } from 'lucide-react'
import { type FormEvent, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, apiErrorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import type { Company, NotificationPreferences, User, UserRole } from '../types'

const blankPreferences:NotificationPreferences={newCandidate:true,application:true,weeklyDigest:true,productUpdate:false}
export default function Settings(){
  const{user,updateCurrentUser,changePassword}=useAuth(),navigate=useNavigate()
  const[profile,setProfile]=useState<User|null>(null),[company,setCompany]=useState<Company|null>(null),[preferences,setPreferences]=useState<NotificationPreferences>(blankPreferences)
  const[password,setPassword]=useState({current:'',next:'',confirm:''}),[invite,setInvite]=useState({email:'',role:'RECRUITER' as UserRole})
  const[invitation,setInvitation]=useState<{token:string;hours:number}|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('')
  useEffect(()=>{Promise.all([api.users.me(),api.company.get(),api.users.preferences()]).then(([nextProfile,nextCompany,nextPreferences])=>{setProfile(nextProfile);setCompany(nextCompany);setPreferences(nextPreferences);updateCurrentUser(nextProfile)}).catch(caught=>setError(apiErrorMessage(caught))).finally(()=>setLoading(false))},[updateCurrentUser])
  const notify=(message:string)=>{setSuccess(message);setError('');window.setTimeout(()=>setSuccess(''),2500)}
  async function saveProfile(event:FormEvent){event.preventDefault();if(!profile)return;setSaving('profile');try{const updated=await api.users.updateMe({name:profile.name,email:profile.email,jobTitle:profile.jobTitle,phone:profile.phone,avatarUrl:profile.avatarUrl});setProfile(updated);updateCurrentUser(updated);notify('Profile updated.')}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving('')}}
  async function saveCompany(event:FormEvent){event.preventDefault();if(!company)return;setSaving('company');try{const updated=await api.company.update({name:company.name,website:company.website,location:company.location,size:company.size});setCompany(updated);if(user)updateCurrentUser({...user,companyName:updated.name});notify('Company settings updated.')}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving('')}}
  async function savePreferences(event:FormEvent){event.preventDefault();setSaving('preferences');try{setPreferences(await api.users.updatePreferences(preferences));notify('Notification preferences updated.')}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving('')}}
  async function savePassword(event:FormEvent){event.preventDefault();const issue=validatePassword(password.next);if(issue){setError(issue);return}if(password.next!==password.confirm){setError('New passwords do not match.');return}setSaving('password');try{await changePassword(password.current,password.next);navigate('/login?passwordChanged=1',{replace:true})}catch(caught){setError(apiErrorMessage(caught));setSaving('')}}
  async function createInvite(event:FormEvent){event.preventDefault();setSaving('invite');setInvitation(null);try{const result=await api.auth.invite({email:invite.email.trim(),role:invite.role});setInvitation({token:result.invitationToken,hours:result.expiresInHours});notify('Invitation created.')}catch(caught){setError(apiErrorMessage(caught))}finally{setSaving('')}}
  if(loading)return <main className="grid min-h-96 place-items-center"><Loader2 className="size-8 animate-spin text-blue-600"/></main>
  const invitationUrl=invitation?`${window.location.origin}/login?invitationToken=${encodeURIComponent(invitation.token)}`:''
  return <main className="p-8"><div><h1 className="page-title">Settings</h1><p className="muted mt-2">Manage your account and recruitment workspace.</p></div>{error&&<p role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{success&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{success}</p>}
    <div className="mt-7 grid gap-6 xl:grid-cols-2">
      {profile&&<Panel icon={UserRound} title="Profile information"><form onSubmit={saveProfile} className="grid gap-4 sm:grid-cols-2"><Field label="Full name" value={profile.name} onChange={value=>setProfile({...profile,name:value})}/><Field label="Email" type="email" value={profile.email} onChange={value=>setProfile({...profile,email:value})}/><Field label="Job title" required={false} value={profile.jobTitle||''} onChange={value=>setProfile({...profile,jobTitle:value||null})}/><Field label="Phone" required={false} value={profile.phone||''} onChange={value=>setProfile({...profile,phone:value||null})}/><div className="sm:col-span-2"><Field label="Avatar URL" required={false} type="url" value={profile.avatarUrl||''} onChange={value=>setProfile({...profile,avatarUrl:value||null})}/></div><Save loading={saving==='profile'}>Save profile</Save></form></Panel>}
      {company&&<Panel icon={Building2} title="Company settings"><form onSubmit={saveCompany} className="grid gap-4 sm:grid-cols-2"><Field disabled={user?.role!=='ADMIN'} label="Company name" value={company.name} onChange={value=>setCompany({...company,name:value})}/><Field disabled={user?.role!=='ADMIN'} label="Website" required={false} type="url" value={company.website||''} onChange={value=>setCompany({...company,website:value||null})}/><Field disabled={user?.role!=='ADMIN'} label="Location" required={false} value={company.location||''} onChange={value=>setCompany({...company,location:value||null})}/><Field disabled={user?.role!=='ADMIN'} label="Company size" required={false} value={company.size||''} onChange={value=>setCompany({...company,size:value||null})}/>{user?.role==='ADMIN'?<Save loading={saving==='company'}>Save company</Save>:<p className="sm:col-span-2 text-sm text-slate-500">Company changes are restricted to administrators.</p>}</form></Panel>}
      <Panel icon={Bell} title="Notification preferences"><form onSubmit={savePreferences}><div className="divide-y">{([['newCandidate','New candidates'],['application','Applications'],['weeklyDigest','Weekly digest'],['productUpdate','Product updates']] as const).map(([key,label])=><label key={key} className="flex items-center justify-between py-3 text-sm font-semibold"><span>{label}</span><input type="checkbox" checked={preferences[key]} onChange={event=>setPreferences(current=>({...current,[key]:event.target.checked}))} className="size-4 accent-blue-600"/></label>)}</div><Save loading={saving==='preferences'}>Save preferences</Save></form></Panel>
      <Panel icon={KeyRound} title="Change password"><form onSubmit={savePassword} className="space-y-4"><Field type="password" label="Current password" value={password.current} onChange={value=>setPassword({...password,current:value})}/><Field type="password" label="New password" value={password.next} onChange={value=>setPassword({...password,next:value})}/><Field type="password" label="Confirm new password" value={password.confirm} onChange={value=>setPassword({...password,confirm:value})}/><p className="text-xs text-slate-500">12–128 characters with uppercase, lowercase, number, and special character.</p><Save loading={saving==='password'}>Change password</Save></form></Panel>
    </div>
    {user?.role==='ADMIN'&&<section className="card mt-6 p-6 sm:p-8"><div className="flex items-center gap-3"><UserPlus className="size-6 text-violet-600"/><div><h2 className="text-xl font-bold">Invite a team member</h2><p className="text-sm text-slate-500">Invitation links expire after 72 hours.</p></div></div><form onSubmit={createInvite} className="mt-6 flex flex-col gap-3 sm:flex-row"><input required type="email" value={invite.email} onChange={event=>setInvite({...invite,email:event.target.value})} className="h-11 flex-1 rounded-lg border px-3" placeholder="colleague@company.com"/><select value={invite.role} onChange={event=>setInvite({...invite,role:event.target.value as UserRole})} className="h-11 rounded-lg border bg-white px-3"><option value="RECRUITER">Recruiter</option><option value="ADMIN">Administrator</option></select><Save loading={saving==='invite'}>Create invitation</Save></form>{invitation&&<label className="mt-4 block text-sm font-semibold text-emerald-800">Invitation URL · expires in {invitation.hours} hours<input readOnly value={invitationUrl} onFocus={event=>event.currentTarget.select()} className="mt-2 w-full rounded-lg border bg-emerald-50 px-3 py-2 font-normal text-slate-700"/></label>}</section>}
  </main>
}
function Panel({icon:Icon,title,children}:{icon:typeof UserRound;title:string;children:React.ReactNode}){return <section className="card p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon className="size-5"/></div><h2 className="text-xl font-bold">{title}</h2></div>{children}</section>}
function Field({label,value,onChange,type='text',required=true,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean;disabled?:boolean}){return <label className="text-sm font-semibold">{label}<input disabled={disabled} required={required} type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-1.5 h-11 w-full rounded-lg border px-3 font-normal disabled:bg-slate-50 disabled:text-slate-500"/></label>}
function Save({children,loading}:{children:React.ReactNode;loading:boolean}){return <button disabled={loading} className="grad-accent flex h-11 items-center justify-center rounded-lg px-5 text-sm font-semibold text-white disabled:opacity-60">{loading?<Loader2 className="size-4 animate-spin"/>:children}</button>}
function validatePassword(value:string){if(value.length<12||value.length>128)return'Password must contain between 12 and 128 characters.';if(!/[A-Z]/.test(value)||!/[a-z]/.test(value)||!/\d/.test(value)||!/[^\w]/.test(value))return'Password must include uppercase, lowercase, number, and special character.';return''}
